frr defaults traditional
hostname leaf-04
log syslog informational
service integrated-vtysh-config
!
vrf VRF-AI
 vni 50004
!
interface lo
 ip address 10.1.0.14/32
!
interface eth1
 description P2P to spine-01
 ip address 10.0.0.7/31
!
interface eth2
 description P2P to spine-02
 ip address 10.0.0.23/31
!
interface vlan80
 vrf VRF-AI
!
interface vlan4004
 vrf VRF-AI
!
router bgp 65004
 no bgp ebgp-requires-policy
 bgp router-id 10.1.0.14
 bgp log-neighbor-changes
 bgp bestpath as-path multipath-relax
 neighbor 10.0.0.6  remote-as 65000
 neighbor 10.0.0.6  description spine-01
 neighbor 10.0.0.6  bfd
 neighbor 10.0.0.6  timers 3 9
 neighbor 10.0.0.22 remote-as 65000
 neighbor 10.0.0.22 description spine-02
 neighbor 10.0.0.22 bfd
 neighbor 10.0.0.22 timers 3 9
 !
 address-family ipv4 unicast
  network 10.1.0.14/32
  neighbor 10.0.0.6  activate
  neighbor 10.0.0.6  soft-reconfiguration inbound
  neighbor 10.0.0.22 activate
  neighbor 10.0.0.22 soft-reconfiguration inbound
  maximum-paths 2
 exit-address-family
 address-family l2vpn evpn
  neighbor 10.0.0.6  activate
  neighbor 10.0.0.22 activate
  advertise-all-vni
 exit-address-family
!
router bgp 65004 vrf VRF-AI
 bgp router-id 10.1.0.14
 address-family ipv4 unicast
  redistribute connected
 exit-address-family
 address-family l2vpn evpn
  advertise ipv4 unicast
  rd 10.1.0.14:50004
  route-target both 65000:50004
 exit-address-family
!
end
