frr version 9.1
frr defaults traditional
hostname spine-01
log syslog informational
no ipv6 forwarding
!
interface eth1
 description P2P to leaf-01
 ip address 10.0.0.0/31
!
interface eth2
 description P2P to leaf-02
 ip address 10.0.0.2/31
!
interface eth3
 description P2P to leaf-03
 ip address 10.0.0.4/31
!
interface eth4
 description P2P to leaf-04
 ip address 10.0.0.6/31
!
interface eth5
 description P2P to leaf-05
 ip address 10.0.0.8/31
!
interface eth6
 description P2P to leaf-06
 ip address 10.0.0.10/31
!
interface eth7
 description P2P to leaf-07
 ip address 10.0.0.12/31
!
interface eth8
 description P2P to leaf-08
 ip address 10.0.0.14/31
!
interface eth9
 description P2P to leaf-09
 ip address 10.0.0.16/31
!
interface eth10
 description P2P to leaf-10
 ip address 10.0.0.18/31
!
interface lo
 ip address 10.1.0.1/32
!
agentx
router bgp 65000
 no bgp ebgp-requires-policy
 bgp router-id 10.1.0.1
 bgp log-neighbor-changes
 bgp bestpath as-path multipath-relax
 neighbor FABRIC peer-group
 neighbor FABRIC bfd
 neighbor FABRIC timers 3 9
 neighbor FABRIC capability extended-nexthop
 neighbor FABRIC password ESI-BGP-INTERNAL
 neighbor 10.0.0.1 remote-as 65001
 neighbor 10.0.0.1 peer-group FABRIC
 neighbor 10.0.0.3 remote-as 65001
 neighbor 10.0.0.3 peer-group FABRIC
 neighbor 10.0.0.5 remote-as 65002
 neighbor 10.0.0.5 peer-group FABRIC
 neighbor 10.0.0.7 remote-as 65002
 neighbor 10.0.0.7 peer-group FABRIC
 neighbor 10.0.0.9 remote-as 65003
 neighbor 10.0.0.9 peer-group FABRIC
 neighbor 10.0.0.11 remote-as 65003
 neighbor 10.0.0.11 peer-group FABRIC
 neighbor 10.0.0.13 remote-as 65004
 neighbor 10.0.0.13 peer-group FABRIC
 neighbor 10.0.0.15 remote-as 65004
 neighbor 10.0.0.15 peer-group FABRIC
 neighbor 10.0.0.17 remote-as 65005
 neighbor 10.0.0.17 peer-group FABRIC
 neighbor 10.0.0.19 remote-as 65005
 neighbor 10.0.0.19 peer-group FABRIC
 !
 address-family ipv4 unicast
  network 10.1.0.1/32
  neighbor FABRIC soft-reconfiguration inbound
  maximum-paths 10
 exit-address-family
 !
 address-family l2vpn evpn
  neighbor FABRIC activate
  neighbor FABRIC attribute-unchanged next-hop
 exit-address-family
!
line vty
