frr version 8.4_git
frr defaults traditional
hostname spine-01
domainname localdomain
log syslog informational
no ipv6 forwarding
!
interface eth1
 description P2P to leaf-01
 ip address 10.0.0.0/31
exit
!
interface eth2
 description P2P to leaf-02
 ip address 10.0.0.2/31
exit
!
interface eth3
 description P2P to leaf-03
 ip address 10.0.0.4/31
exit
!
interface eth4
 description P2P to leaf-04
 ip address 10.0.0.6/31
exit
!
interface eth5
 description P2P to border-01
 ip address 10.0.0.8/31
exit
!
interface eth6
 description P2P to border-02
 ip address 10.0.0.10/31
exit
!
interface lo
 ip address 10.1.0.1/32
exit
!
router bgp 65000
 no bgp ebgp-requires-policy
 bgp router-id 10.1.0.1
 bgp log-neighbor-changes
 bgp bestpath as-path multipath-relax
 neighbor FABRIC peer-group
 neighbor FABRIC bfd
 neighbor FABRIC timers 3 9
 neighbor FABRIC capability extended-nexthop
 neighbor 10.0.0.1 remote-as 65001
 neighbor 10.0.0.1 peer-group FABRIC
 neighbor 10.0.0.1 description leaf-01
 neighbor 10.0.0.3 remote-as 65002
 neighbor 10.0.0.3 peer-group FABRIC
 neighbor 10.0.0.3 description leaf-02
 neighbor 10.0.0.5 remote-as 65003
 neighbor 10.0.0.5 peer-group FABRIC
 neighbor 10.0.0.5 description leaf-03
 neighbor 10.0.0.7 remote-as 65004
 neighbor 10.0.0.7 peer-group FABRIC
 neighbor 10.0.0.7 description leaf-04
 neighbor 10.0.0.9 remote-as 65005
 neighbor 10.0.0.9 peer-group FABRIC
 neighbor 10.0.0.9 description border-01
 neighbor 10.0.0.11 remote-as 65005
 neighbor 10.0.0.11 peer-group FABRIC
 neighbor 10.0.0.11 description border-02
 !
 address-family ipv4 unicast
  network 10.1.0.1/32
  neighbor FABRIC soft-reconfiguration inbound
  maximum-paths 6
 exit-address-family
 !
 address-family l2vpn evpn
  neighbor FABRIC activate
  neighbor FABRIC attribute-unchanged next-hop
 exit-address-family
exit
!
