frr version 9.1
frr defaults traditional
hostname leaf-03
log syslog informational
no ipv6 forwarding
!
vrf VRF-STAFF
 vni 50020
!
vrf VRF-ADMINISTRATION
 vni 50010
!
interface lo
 ip address 10.1.0.13/32
!
interface eth1
 description P2P to spine-01
 ip address 10.0.0.5/31
!
interface eth2
 description P2P to spine-02
 ip address 10.0.1.5/31
!
interface vlan30
 description LMS-STAFF anycast gateway
 vrf VRF-STAFF
 ip address 192.168.30.1/24
!
interface vlan40
 description SERVICES-WEB anycast gateway
 vrf VRF-STAFF
 ip address 192.168.40.1/24
!
interface vlan50
 description CORE-INFRA anycast gateway
 vrf VRF-STAFF
 ip address 192.168.50.1/24
!
interface vlan60
 description HR-FINANCE anycast gateway
 vrf VRF-ADMINISTRATION
 ip address 192.168.60.1/24
!
agentx
router bgp 65002
 no bgp ebgp-requires-policy
 bgp router-id 10.1.0.13
 bgp log-neighbor-changes
 bgp bestpath as-path multipath-relax
 neighbor FABRIC peer-group
 neighbor FABRIC bfd
 neighbor FABRIC timers 3 9
 neighbor FABRIC password ESI-BGP-INTERNAL
 neighbor FABRIC allowas-in 2
 neighbor 10.0.0.4 remote-as 65000
 neighbor 10.0.0.4 peer-group FABRIC
 neighbor 10.0.1.4 remote-as 65000
 neighbor 10.0.1.4 peer-group FABRIC
 !
 address-family ipv4 unicast
  network 10.1.0.13/32
  network 192.168.50.0/24
  neighbor FABRIC soft-reconfiguration inbound
  maximum-paths 2
 exit-address-family
 !
 address-family l2vpn evpn
  neighbor FABRIC activate
  neighbor FABRIC allowas-in 2
  advertise-all-vni
 exit-address-family
!
router bgp 65002 vrf VRF-STAFF
 address-family ipv4 unicast
  redistribute connected
  import vrf default
 exit-address-family
 address-family l2vpn evpn
  advertise ipv4 unicast
  rd 10.1.0.13:50020
  route-target both 65000:50020
 exit-address-family
!
router bgp 65002 vrf VRF-ADMINISTRATION
 address-family ipv4 unicast
  redistribute connected
 exit-address-family
 address-family l2vpn evpn
  advertise ipv4 unicast
  rd 10.1.0.13:50010
  route-target both 65000:50010
 exit-address-family
!
! --- Core service ESI multihoming - Leaf-03 ---
interface eth7
 description Link-to-DNS-Server
 evpn mh es-id 303
 evpn mh es-sys-mac 00:11:22:33:44:02
!
interface eth8
 description Link-to-DHCP-Server
 evpn mh es-id 304
 evpn mh es-sys-mac 00:11:22:33:44:02
!
interface eth9
 description Link-to-NTP-Server
 evpn mh es-id 305
 evpn mh es-sys-mac 00:11:22:33:44:02
!
! --- Paire 02 ADMIN (Ikram) - Leaf-03 ---
interface eth3
 description Link-to-FTP-Server
!
interface eth4
 description Link-to-Server-Admin-01
 evpn mh es-id 301
 evpn mh es-sys-mac 00:11:22:33:44:02
!
interface eth6
 description Link-to-Server-Admin-02
 evpn mh es-id 302
 evpn mh es-sys-mac 00:11:22:33:44:02
!
line vty
