frr version 9.1
frr defaults traditional
hostname leaf-07
log syslog informational
no ipv6 forwarding
!
vrf VRF-STAFF
 vni 50020
!
interface lo
 ip address 10.1.0.17/32
!
interface eth1
 description P2P to spine-01
 ip address 10.0.0.13/31
!
interface eth2
 description P2P to spine-02
 ip address 10.0.1.13/31
!
router bgp 65004
 no bgp ebgp-requires-policy
 bgp router-id 10.1.0.17
 bgp log-neighbor-changes
 bgp bestpath as-path multipath-relax
 neighbor FABRIC peer-group
 neighbor FABRIC bfd
 neighbor FABRIC timers 3 9
 neighbor FABRIC password ESI-BGP-SECRET
 neighbor FABRIC allowas-in 2
 neighbor 10.0.0.12 remote-as 65000
 neighbor 10.0.0.12 peer-group FABRIC
 neighbor 10.0.1.12 remote-as 65000
 neighbor 10.0.1.12 peer-group FABRIC
 !
 address-family ipv4 unicast
  network 10.1.0.17/32
  neighbor FABRIC soft-reconfiguration inbound
  maximum-paths 2
 exit-address-family
 !
 address-family l2vpn evpn
  neighbor FABRIC activate
  neighbor FABRIC allowas-in 2
  advertise-all-vni
 exit-address-family
!

router bgp 65004 vrf VRF-STAFF
 address-family ipv4 unicast
  redistribute connected
 exit-address-family
 address-family l2vpn evpn
  advertise ipv4 unicast
  rd 10.1.0.17:50020
  route-target both 65000:50020
 exit-address-family
!
! --- Paire 04 Storage (Ikram) ---
interface eth3
 description Link-to-Server-Storage-01
 evpn mh es-id 7
 evpn mh es-sys-mac 00:11:22:33:44:04
!
line vty
