frr version 9.1
frr defaults traditional
hostname internet-router-02
log syslog informational
!
interface lo
 ip address 100.64.10.2/32
!
interface eth1
 ip address 198.18.2.1/24
!
interface eth2
 ip address 198.18.12.1/30
!
router bgp 64411
 no bgp ebgp-requires-policy
 bgp router-id 100.64.10.2
 neighbor 198.18.12.2 remote-as 64400
 neighbor 198.18.12.2 password ESI-BGP-SECRET
 address-family ipv4 unicast
  network 198.18.2.0/24
  network 100.64.10.2/32
  neighbor 198.18.12.2 activate
 exit-address-family
!
line vty
