frr version 9.1
frr defaults traditional
hostname leaf-02
log syslog informational
no ipv6 forwarding
!
vrf VRF-PEDAGOGY
 vni 50030
!
vrf VRF-STAFF
 vni 50020
!
vrf VRF-PUBLIC
 vni 50040
!
vrf VRF-ORIENTATION
 vni 50050
!
interface lo
 ip address 10.1.0.12/32
!
interface eth1
 description P2P to spine-01
 ip address 10.0.0.3/31
!
interface eth2
 description P2P to spine-02
 ip address 10.0.1.3/31
!
interface eth3
 description eBGP to isp-router-02
 ip address 203.0.113.5/30
!
router bgp 65001
 no bgp ebgp-requires-policy
 bgp router-id 10.1.0.12
 bgp log-neighbor-changes
 bgp bestpath as-path multipath-relax
 neighbor FABRIC peer-group
 neighbor FABRIC bfd
 neighbor FABRIC timers 3 9
 neighbor FABRIC password ESI-BGP-SECRET
 neighbor FABRIC allowas-in 2
 neighbor ISP-EXT peer-group
 neighbor ISP-EXT password ESI-BGP-SECRET
 neighbor 10.0.0.2 remote-as 65000
 neighbor 10.0.0.2 peer-group FABRIC
 neighbor 10.0.1.2 remote-as 65000
 neighbor 10.0.1.2 peer-group FABRIC
 neighbor 203.0.113.6 remote-as 64501
 neighbor 203.0.113.6 peer-group ISP-EXT
 !
 address-family ipv4 unicast
  network 10.1.0.12/32
  neighbor FABRIC soft-reconfiguration inbound
  neighbor ISP-EXT activate
  maximum-paths 2
 exit-address-family
 !
 address-family l2vpn evpn
  neighbor FABRIC activate
  neighbor FABRIC allowas-in 2
  advertise-all-vni
 exit-address-family
!
ip route 0.0.0.0/0 Null0 vrf VRF-PEDAGOGY
ip route 0.0.0.0/0 Null0 vrf VRF-STAFF
router bgp 65001 vrf VRF-PEDAGOGY
 address-family ipv4 unicast
  redistribute static
 exit-address-family
 address-family l2vpn evpn
  advertise ipv4 unicast
  rd 10.1.0.12:50030
  route-target both 65000:50030
 exit-address-family
!
router bgp 65001 vrf VRF-STAFF
 address-family ipv4 unicast
  redistribute connected
  redistribute static
 exit-address-family
 address-family l2vpn evpn
  advertise ipv4 unicast
  rd 10.1.0.12:50020
  route-target both 65000:50020
 exit-address-family
!
router bgp 65001 vrf VRF-PUBLIC
 address-family ipv4 unicast
  redistribute static
 exit-address-family
 address-family l2vpn evpn
  advertise ipv4 unicast
  rd 10.1.0.12:50040
  route-target both 65000:50040
 exit-address-family
!
router bgp 65001 vrf VRF-ORIENTATION
 address-family ipv4 unicast
  redistribute static
 exit-address-family
 address-family l2vpn evpn
  advertise ipv4 unicast
  rd 10.1.0.12:50050
  route-target both 65000:50050
 exit-address-family
!
# --- INTERFACES MULTI-HOMING (ESI) ---

interface eth5
 description Link-to-Firewall-02-ESI
 # Doit être identique au Leaf-01
 evpn mh es-id 1
 evpn mh es-sys-mac 00:11:22:33:44:01
exit
!
interface eth7
 description Link-to-Server-DMZ-01-ESI
 # Doit être identique au Leaf-01
 evpn mh es-id 2
 evpn mh es-sys-mac 00:11:22:33:44:01
exit
!
line vty