frr version 9.1
frr defaults traditional
hostname leaf-02
log syslog informational
no ipv6 forwarding
!
vrf VRF-PEDAGOGY
 vni 50030
!
vrf VRF-PUBLIC
 vni 50040
!
vrf VRF-ORIENTATION
 vni 50050
!
interface lo
 ip address 10.1.0.12/32
!
interface eth1
 description P2P to spine-01
 ip address 10.0.0.3/31
!
interface eth2
 description P2P to spine-02
 ip address 10.0.1.3/31
!
interface eth3
 description eBGP to isp-router-02
 ip address 203.0.113.5/30
!
agentx
router bgp 65001
 no bgp ebgp-requires-policy
 bgp router-id 10.1.0.12
 bgp log-neighbor-changes
 bgp bestpath as-path multipath-relax
 neighbor FABRIC peer-group
 neighbor FABRIC bfd
 neighbor FABRIC timers 3 9
 neighbor FABRIC password ESI-BGP-INTERNAL
 neighbor FABRIC allowas-in 2
 neighbor ISP-EXT peer-group
 neighbor ISP-EXT password ESI-BGP-EXTERNAL
 neighbor 10.0.0.2 remote-as 65000
 neighbor 10.0.0.2 peer-group FABRIC
 neighbor 10.0.1.2 remote-as 65000
 neighbor 10.0.1.2 peer-group FABRIC
 neighbor 203.0.113.6 remote-as 64501
 neighbor 203.0.113.6 peer-group ISP-EXT
 !
 address-family ipv4 unicast
  network 10.1.0.12/32
  neighbor FABRIC soft-reconfiguration inbound
    neighbor ISP-EXT soft-reconfiguration inbound
  neighbor ISP-EXT activate
  neighbor 203.0.113.6 prefix-list ISP-IN in
  neighbor 203.0.113.6 prefix-list ISP-OUT out
  neighbor 203.0.113.6 maximum-prefix 100 80
  maximum-paths 2
 exit-address-family
 !
 address-family l2vpn evpn
  neighbor FABRIC activate
  neighbor FABRIC allowas-in 2
  advertise-all-vni
 exit-address-family
!
ip prefix-list ISP-IN seq 5 permit 0.0.0.0/0
ip prefix-list ISP-IN seq 10 deny any
ip prefix-list ISP-OUT seq 5 deny 10.0.0.0/8 le 32
ip prefix-list ISP-OUT seq 10 deny 172.16.0.0/12 le 32
ip prefix-list ISP-OUT seq 15 deny 192.168.0.0/16 le 32
ip prefix-list ISP-OUT seq 20 permit any
router bgp 65001 vrf VRF-PEDAGOGY
 address-family ipv4 unicast
  redistribute static
 exit-address-family
 address-family l2vpn evpn
  advertise ipv4 unicast
  rd 10.1.0.12:50030
  route-target both 65000:50030
 exit-address-family
!
router bgp 65001 vrf VRF-PUBLIC
 address-family ipv4 unicast
  redistribute static
 exit-address-family
 address-family l2vpn evpn
  advertise ipv4 unicast
  rd 10.1.0.12:50040
  route-target both 65000:50040
 exit-address-family
!
router bgp 65001 vrf VRF-ORIENTATION
 address-family ipv4 unicast
  redistribute static
 exit-address-family
 address-family l2vpn evpn
  advertise ipv4 unicast
  rd 10.1.0.12:50050
  route-target both 65000:50050
 exit-address-family
!
line vty
