frr version 8.4_git
frr defaults traditional
hostname leaf-02
log syslog informational
no ipv6 forwarding
!
vrf VRF-ORIENTATION
 vni 50050
exit-vrf
!
vrf VRF-PEDAGOGY
 vni 50030
 ip route 0.0.0.0/0 Null0
exit-vrf
!
vrf VRF-PUBLIC
 vni 50040
exit-vrf
!
vrf VRF-STAFF
 vni 50020
 ip route 0.0.0.0/0 Null0
exit-vrf
!
interface eth1
 description P2P to spine-01
 ip address 10.0.0.3/31
exit
!
interface eth2
 description P2P to spine-02
 ip address 10.0.1.3/31
exit
!
interface eth3
 description eBGP to isp-router-02
 ip address 203.0.113.5/30
exit
!
interface eth5
 description Link-to-Firewall-02-ESI
exit
!
interface lo
 ip address 10.1.0.12/32
exit
!
router bgp 65001
 bgp router-id 10.1.0.12
 bgp log-neighbor-changes
 no bgp ebgp-requires-policy
 bgp bestpath as-path multipath-relax
 neighbor FABRIC peer-group
 neighbor FABRIC bfd
 neighbor FABRIC password ESI-BGP-SECRET
 neighbor FABRIC timers 3 9
 neighbor ISP-EXT peer-group
 neighbor ISP-EXT password ESI-BGP-SECRET
 neighbor 10.0.0.2 remote-as 65000
 neighbor 10.0.0.2 peer-group FABRIC
 neighbor 10.0.1.2 remote-as 65000
 neighbor 10.0.1.2 peer-group FABRIC
 neighbor 203.0.113.6 remote-as 64501
 neighbor 203.0.113.6 peer-group ISP-EXT
 !
 address-family ipv4 unicast
  network 10.1.0.12/32
  neighbor FABRIC soft-reconfiguration inbound
  neighbor FABRIC allowas-in 2
  maximum-paths 2
 exit-address-family
 !
 address-family l2vpn evpn
  neighbor FABRIC activate
  neighbor FABRIC allowas-in 2
  advertise-all-vni
 exit-address-family
exit
!
router bgp 65001 vrf VRF-PEDAGOGY
 !
 address-family ipv4 unicast
  redistribute static
 exit-address-family
 !
 address-family l2vpn evpn
  advertise ipv4 unicast
  rd 10.1.0.12:50030
  route-target import 65000:50030
  route-target export 65000:50030
 exit-address-family
exit
!
router bgp 65001 vrf VRF-STAFF
 !
 address-family ipv4 unicast
  redistribute connected
  redistribute static
 exit-address-family
 !
 address-family l2vpn evpn
  advertise ipv4 unicast
  rd 10.1.0.12:50020
  route-target import 65000:50020
  route-target export 65000:50020
 exit-address-family
exit
!
router bgp 65001 vrf VRF-PUBLIC
 !
 address-family ipv4 unicast
  redistribute static
 exit-address-family
 !
 address-family l2vpn evpn
  advertise ipv4 unicast
  rd 10.1.0.12:50040
  route-target import 65000:50040
  route-target export 65000:50040
 exit-address-family
exit
!
router bgp 65001 vrf VRF-ORIENTATION
 !
 address-family ipv4 unicast
  redistribute static
 exit-address-family
 !
 address-family l2vpn evpn
  advertise ipv4 unicast
  rd 10.1.0.12:50050
  route-target import 65000:50050
  route-target export 65000:50050
 exit-address-family
exit
!
