---
all:
  vars:
    ansible_user: admin
    ansible_password: admin
    ansible_network_os: eos
    ansible_connection: httpapi
    ansible_httpapi_use_ssl: true
    ansible_httpapi_port: 443
    ansible_httpapi_validate_certs: false
    ansible_become: true                  
    ansible_become_method: enable         

  children:
    spine:
      hosts:
        spine-01:
          ansible_host: 172.100.100.11

    leafs:
      hosts:
        leaf-01:
          ansible_host: 172.100.100.21
          leaf_asn: 65001
          host_vlan: 10
          host_subnet: 10.10.10.0/24
          host_gw: 10.10.10.1/24

    fabric:
      children:
        spine:
        leafs: