frr version 9.1
frr defaults traditional
hostname isp-router-03-bac
log syslog informational
!
interface lo
 ip address 100.64.0.3/32
!
interface eth1
 description eBGP to border-router-01 (BAC)
 ip address 203.0.113.6/30
!
router bgp 64501
 no bgp ebgp-requires-policy
 bgp router-id 100.64.0.3
 neighbor 203.0.113.5 remote-as 65010
 neighbor 203.0.113.5 password ESI-BGP-EXTERNAL
 address-family ipv4 unicast
  network 100.64.0.3/32
  network 203.0.113.4/30
  neighbor 203.0.113.5 activate
  neighbor 203.0.113.5 default-originate
 exit-address-family
!
line vty
