frr version 9.1
frr defaults traditional
hostname leaf-01
log syslog informational
no ipv6 forwarding
!
vrf VRF-PEDAGOGY
 vni 50030
!
vrf VRF-PUBLIC
 vni 50040
!
vrf VRF-ORIENTATION
 vni 50050
!
vrf VRF-WIFI-CTRL
 vni 50060
!
interface lo
 ip address 10.1.0.11/32
!
interface eth1
 description P2P to spine-01
 ip address 10.0.0.1/31
!
interface eth2
 description P2P to spine-02
 ip address 10.0.1.1/31
!
interface eth3
 description eBGP to isp-router-01
 ip address 203.0.113.1/30
!
interface eth4
 description eBGP to isp-router-03
 ip address 203.0.114.1/30
!
interface eth8
 description Campus WiFi management uplink
 vrf VRF-WIFI-CTRL
 ip address 10.200.0.1/30
!
interface vlan120
 description WIFI-CTRL-MGMT bridge VLAN
 vrf VRF-WIFI-CTRL
!
router bgp 65001
 no bgp ebgp-requires-policy
 bgp router-id 10.1.0.11
 bgp log-neighbor-changes
 bgp bestpath as-path multipath-relax
 neighbor FABRIC peer-group
 neighbor FABRIC bfd
 neighbor FABRIC timers 3 9
 neighbor FABRIC password ESI-BGP-SECRET
 neighbor FABRIC allowas-in 2
 neighbor ISP-EXT peer-group
 neighbor ISP-EXT password ESI-BGP-SECRET
 neighbor 10.0.0.0 remote-as 65000
 neighbor 10.0.0.0 peer-group FABRIC
 neighbor 10.0.1.0 remote-as 65000
 neighbor 10.0.1.0 peer-group FABRIC
 neighbor 203.0.113.2 remote-as 64500
 neighbor 203.0.113.2 peer-group ISP-EXT
 neighbor 203.0.114.2 remote-as 64502
 neighbor 203.0.114.2 peer-group ISP-EXT
 !
 address-family ipv4 unicast
  network 10.1.0.11/32
  neighbor FABRIC soft-reconfiguration inbound
  neighbor ISP-EXT activate
  maximum-paths 2
 exit-address-family
 !
 address-family l2vpn evpn
  neighbor FABRIC activate
  neighbor FABRIC allowas-in 2
  advertise-all-vni
 exit-address-family
!
ip route 0.0.0.0/0 Null0 vrf VRF-PEDAGOGY
ip route 192.168.10.100/32 10.200.0.2 vrf VRF-WIFI-CTRL
ip route 192.168.30.0/24 192.168.1.254 nexthop-vrf default vrf VRF-PEDAGOGY
ip route 192.168.40.0/24 192.168.1.254 nexthop-vrf default vrf VRF-PEDAGOGY
ip route 192.168.50.0/24 192.168.1.254 nexthop-vrf default vrf VRF-PEDAGOGY
ip route 192.168.60.0/24 192.168.1.254 nexthop-vrf default vrf VRF-PEDAGOGY
router bgp 65001 vrf VRF-PEDAGOGY
 address-family ipv4 unicast
  redistribute static
 exit-address-family
 address-family l2vpn evpn
  advertise ipv4 unicast
  rd 10.1.0.11:50030
  route-target both 65000:50030
 exit-address-family
!
router bgp 65001 vrf VRF-PUBLIC
 address-family ipv4 unicast
  redistribute static
 exit-address-family
 address-family l2vpn evpn
  advertise ipv4 unicast
  rd 10.1.0.11:50040
  route-target both 65000:50040
 exit-address-family
!
router bgp 65001 vrf VRF-ORIENTATION
 address-family ipv4 unicast
  redistribute static
 exit-address-family
 address-family l2vpn evpn
  advertise ipv4 unicast
  rd 10.1.0.11:50050
  route-target both 65000:50050
 exit-address-family
!
router bgp 65001 vrf VRF-WIFI-CTRL
 address-family ipv4 unicast
  redistribute static
 exit-address-family
 address-family l2vpn evpn
  advertise ipv4 unicast
  rd 10.1.0.11:50060
  route-target both 65000:50060
 exit-address-family
!
line vty
