frr defaults traditional
hostname leaf-03
log syslog informational
service integrated-vtysh-config
!
vrf VRF-SERVICES
 vni 50003
!
interface lo
 ip address 10.1.0.13/32
!
interface eth1
 description P2P to spine-01
 ip address 10.0.0.5/31
!
interface eth2
 description P2P to spine-02
 ip address 10.0.0.21/31
!
interface vlan50
 vrf VRF-SERVICES
!
interface vlan60
 vrf VRF-SERVICES
!
interface vlan70
 vrf VRF-SERVICES
!
interface vlan4003
 vrf VRF-SERVICES
!
router bgp 65003
 no bgp ebgp-requires-policy
 bgp router-id 10.1.0.13
 bgp log-neighbor-changes
 bgp bestpath as-path multipath-relax
 neighbor 10.0.0.4  remote-as 65000
 neighbor 10.0.0.4  description spine-01
 neighbor 10.0.0.4  bfd
 neighbor 10.0.0.4  timers 3 9
 neighbor 10.0.0.20 remote-as 65000
 neighbor 10.0.0.20 description spine-02
 neighbor 10.0.0.20 bfd
 neighbor 10.0.0.20 timers 3 9
 !
 address-family ipv4 unicast
  network 10.1.0.13/32
  neighbor 10.0.0.4  activate
  neighbor 10.0.0.4  soft-reconfiguration inbound
  neighbor 10.0.0.20 activate
  neighbor 10.0.0.20 soft-reconfiguration inbound
  maximum-paths 2
 exit-address-family
 address-family l2vpn evpn
  neighbor 10.0.0.4  activate
  neighbor 10.0.0.20 activate
  advertise-all-vni
 exit-address-family
!
router bgp 65003 vrf VRF-SERVICES
 bgp router-id 10.1.0.13
 address-family ipv4 unicast
  redistribute connected
 exit-address-family
 address-family l2vpn evpn
  advertise ipv4 unicast
  rd 10.1.0.13:50003
  route-target both 65000:50003
 exit-address-family
!
end
