frr defaults traditional
hostname leaf-02
log syslog informational
service integrated-vtysh-config
!
vrf VRF-RESEARCH
 vni 50002
!
interface lo
 ip address 10.1.0.12/32
!
interface eth1
 description P2P to spine-01
 ip address 10.0.0.3/31
!
interface eth2
 description P2P to spine-02
 ip address 10.0.0.19/31
!
interface vlan30
 vrf VRF-RESEARCH
!
interface vlan40
 vrf VRF-RESEARCH
!
interface vlan4002
 vrf VRF-RESEARCH
!
router bgp 65002
 no bgp ebgp-requires-policy
 bgp router-id 10.1.0.12
 bgp log-neighbor-changes
 bgp bestpath as-path multipath-relax
 neighbor 10.0.0.2  remote-as 65000
 neighbor 10.0.0.2  description spine-01
 neighbor 10.0.0.2  bfd
 neighbor 10.0.0.2  timers 3 9
 neighbor 10.0.0.18 remote-as 65000
 neighbor 10.0.0.18 description spine-02
 neighbor 10.0.0.18 bfd
 neighbor 10.0.0.18 timers 3 9
 !
 address-family ipv4 unicast
  network 10.1.0.12/32
  neighbor 10.0.0.2  activate
  neighbor 10.0.0.2  soft-reconfiguration inbound
  neighbor 10.0.0.18 activate
  neighbor 10.0.0.18 soft-reconfiguration inbound
  maximum-paths 2
 exit-address-family
 address-family l2vpn evpn
  neighbor 10.0.0.2  activate
  neighbor 10.0.0.18 activate
  advertise-all-vni
 exit-address-family
!
router bgp 65002 vrf VRF-RESEARCH
 bgp router-id 10.1.0.12
 address-family ipv4 unicast
  redistribute connected
 exit-address-family
 address-family l2vpn evpn
  advertise ipv4 unicast
  rd 10.1.0.12:50002
  route-target both 65000:50002
 exit-address-family
!
end
