frr version 8.4_git
frr defaults traditional
hostname spine-02
domainname localdomain
log syslog informational
no ipv6 forwarding
!
interface eth1
 description P2P to leaf-01
 ip address 10.0.0.16/31
exit
!
interface eth2
 description P2P to leaf-02
 ip address 10.0.0.18/31
exit
!
interface eth3
 description P2P to leaf-03
 ip address 10.0.0.20/31
exit
!
interface eth4
 description P2P to leaf-04
 ip address 10.0.0.22/31
exit
!
interface eth5
 description P2P to border-01
 ip address 10.0.0.24/31
exit
!
interface eth6
 description P2P to border-02
 ip address 10.0.0.26/31
exit
!
interface lo
 ip address 10.1.0.2/32
exit
!
router bgp 65000
 no bgp ebgp-requires-policy
 bgp router-id 10.1.0.2
 bgp log-neighbor-changes
 bgp bestpath as-path multipath-relax
 neighbor FABRIC peer-group
 neighbor FABRIC bfd
 neighbor FABRIC timers 3 9
 neighbor FABRIC capability extended-nexthop
 neighbor 10.0.0.17 remote-as 65001
 neighbor 10.0.0.17 peer-group FABRIC
 neighbor 10.0.0.17 description leaf-01
 neighbor 10.0.0.19 remote-as 65002
 neighbor 10.0.0.19 peer-group FABRIC
 neighbor 10.0.0.19 description leaf-02
 neighbor 10.0.0.21 remote-as 65003
 neighbor 10.0.0.21 peer-group FABRIC
 neighbor 10.0.0.21 description leaf-03
 neighbor 10.0.0.23 remote-as 65004
 neighbor 10.0.0.23 peer-group FABRIC
 neighbor 10.0.0.23 description leaf-04
 neighbor 10.0.0.25 remote-as 65005
 neighbor 10.0.0.25 peer-group FABRIC
 neighbor 10.0.0.25 description border-01
 neighbor 10.0.0.27 remote-as 65005
 neighbor 10.0.0.27 peer-group FABRIC
 neighbor 10.0.0.27 description border-02
 !
 address-family ipv4 unicast
  network 10.1.0.2/32
  neighbor FABRIC soft-reconfiguration inbound
  maximum-paths 6
 exit-address-family
 !
 address-family l2vpn evpn
  neighbor FABRIC activate
  neighbor FABRIC attribute-unchanged next-hop
 exit-address-family
exit
!
