global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s
  external_labels:
    lab: esi-datacenter
    environment: simulation

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: frr-exporter
    metrics_path: /metrics/metrics
    fallback_scrape_protocol: PrometheusText0.0.4
    static_configs:
      - targets: ["frr-exporter:9342"]
        labels:
          service: network-telemetry
          owner: netops

  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          service: monitoring-core

  - job_name: grafana
    metrics_path: /metrics
    static_configs:
      - targets: ["grafana:3000"]
        labels:
          service: dashboards
