frr version 9.1
frr defaults traditional
hostname isp-router-03
log syslog informational
!
interface lo
 ip address 100.64.0.3/32
!
interface eth1
 ip address 203.0.114.2/30
!
router bgp 64502
 no bgp ebgp-requires-policy
 bgp router-id 100.64.0.3
 neighbor 203.0.114.1 remote-as 65001
 neighbor 203.0.114.1 password ESI-BGP-SECRET
 address-family ipv4 unicast
  network 100.64.0.3/32
  neighbor 203.0.114.1 activate
 exit-address-family
!
line vty
