frr version 9.1
frr defaults traditional
hostname internet-router-01
log syslog informational
!
interface lo
 ip address 100.64.10.1/32
!
interface eth1
 ip address 198.18.1.1/24
!
interface eth2
 ip address 198.18.11.1/30
!
interface eth3
 ip address 198.18.3.1/24
!
interface eth4
 ip address 198.18.4.1/24
!
router bgp 64410
 no bgp ebgp-requires-policy
 bgp router-id 100.64.10.1
 neighbor 198.18.11.2 remote-as 64400
 neighbor 198.18.11.2 password ESI-BGP-SECRET
 address-family ipv4 unicast
  network 198.18.1.0/24
  network 198.18.3.0/24
    network 198.18.4.0/24
  network 100.64.10.1/32
  neighbor 198.18.11.2 activate
 exit-address-family
!
line vty
