host = world {
    address = 0.0.0.0/0
    key = ESI@Secret2024
}

group = super-admins {
    service = shell {
        default command = permit
        default attribute = permit
        set priv-lvl = 15
    }
}

group = net-admins {
    service = shell {
        
        default command = permit
        default attribute = permit
        set priv-lvl = 10
    }
}

group = etudiants {
    service = shell {
        default command = permit
        default attribute = permit
        set priv-lvl = 3
    }
}

user = admin1 {
    password = clear Admin@2024
    member = super-admins
}

user = netadmin1 {
    password = clear Net@2024
    member = net-admins
}

user = etudiant1 {
    password = clear 123456
    member = etudiants
}