frr defaults traditional
hostname border-01
log syslog informational
service integrated-vtysh-config
!
vrf VRF-PEDAGOGY
 vni 50001
!
vrf VRF-RESEARCH
 vni 50002
!
vrf VRF-SERVICES
 vni 50003
!
vrf VRF-AI
 vni 50004
!
interface lo
 ip address 10.1.0.21/32
!
interface eth1
 description P2P to spine-01
 ip address 10.0.0.9/31
!
interface eth2
 description P2P to spine-02
 ip address 10.0.0.25/31
!
interface eth3
 description External — Algérie Télécom fibre (simulated)
 ip address 203.0.113.1/30
!
interface vlan4001
 vrf VRF-PEDAGOGY
!
interface vlan4002
 vrf VRF-RESEARCH
!
interface vlan4003
 vrf VRF-SERVICES
!
interface vlan4004
 vrf VRF-AI
!
router bgp 65005
 no bgp ebgp-requires-policy
 bgp router-id 10.1.0.21
 bgp log-neighbor-changes
 bgp bestpath as-path multipath-relax
 neighbor 10.0.0.8  remote-as 65000
 neighbor 10.0.0.8  description spine-01
 neighbor 10.0.0.8  bfd
 neighbor 10.0.0.8  timers 3 9
 neighbor 10.0.0.24 remote-as 65000
 neighbor 10.0.0.24 description spine-02
 neighbor 10.0.0.24 bfd
 neighbor 10.0.0.24 timers 3 9
 !
 address-family ipv4 unicast
  network 10.1.0.21/32
  neighbor 10.0.0.8  activate
  neighbor 10.0.0.8  soft-reconfiguration inbound
  neighbor 10.0.0.24 activate
  neighbor 10.0.0.24 soft-reconfiguration inbound
  maximum-paths 2
 exit-address-family
 address-family l2vpn evpn
  neighbor 10.0.0.8  activate
  neighbor 10.0.0.24 activate
  advertise-all-vni
 exit-address-family
!
router bgp 65005 vrf VRF-PEDAGOGY
 bgp router-id 10.1.0.21
 address-family ipv4 unicast
  redistribute connected
 exit-address-family
 address-family l2vpn evpn
  advertise ipv4 unicast
  rd 10.1.0.21:50001
  route-target both 65000:50001
 exit-address-family
!
router bgp 65005 vrf VRF-RESEARCH
 bgp router-id 10.1.0.21
 address-family ipv4 unicast
  redistribute connected
 exit-address-family
 address-family l2vpn evpn
  advertise ipv4 unicast
  rd 10.1.0.21:50002
  route-target both 65000:50002
 exit-address-family
!
router bgp 65005 vrf VRF-SERVICES
 bgp router-id 10.1.0.21
 address-family ipv4 unicast
  redistribute connected
 exit-address-family
 address-family l2vpn evpn
  advertise ipv4 unicast
  rd 10.1.0.21:50003
  route-target both 65000:50003
 exit-address-family
!
router bgp 65005 vrf VRF-AI
 bgp router-id 10.1.0.21
 address-family ipv4 unicast
  redistribute connected
 exit-address-family
 address-family l2vpn evpn
  advertise ipv4 unicast
  rd 10.1.0.21:50004
  route-target both 65000:50004
 exit-address-family
!
end
