frr version 9.1
frr defaults traditional
hostname isp-router-01
log syslog informational
!
interface lo
 ip address 100.64.0.1/32
!
interface eth1
 ip address 203.0.113.2/30
!
interface eth2
 ip address 198.18.13.2/30
!
ip route 0.0.0.0/0 Null0
!
router bgp 64500
 no bgp ebgp-requires-policy
 bgp router-id 100.64.0.1
 neighbor 203.0.113.1 remote-as 65001
 neighbor 203.0.113.1 password ESI-BGP-SECRET
 neighbor 198.18.13.1 remote-as 64400
 neighbor 198.18.13.1 password ESI-BGP-SECRET
 address-family ipv4 unicast
  network 100.64.0.1/32
    network 203.0.113.0/30
  network 0.0.0.0/0
  neighbor 203.0.113.1 activate
  neighbor 198.18.13.1 activate
 exit-address-family
!
line vty
