frr version 9.1
frr defaults traditional
hostname isp-router-02
log syslog informational
!
interface lo
 ip address 100.64.0.2/32
!
interface eth1
 ip address 203.0.113.6/30
!
ip route 0.0.0.0/0 Null0
!
router bgp 64501
 no bgp ebgp-requires-policy
 bgp router-id 100.64.0.2
 neighbor 203.0.113.5 remote-as 65001
 neighbor 203.0.113.5 password ESI-BGP-SECRET
 address-family ipv4 unicast
  network 100.64.0.2/32
  network 0.0.0.0/0
  neighbor 203.0.113.5 activate
 exit-address-family
!
line vty
