
# =============================================================================
# ESI Data Center — Leaf-06 Host Variables
# Pod: Storage (pod_id=3) | ESI pair: leaf-06 ↔ leaf-05
# Management IP: 172.20.20.26
# =============================================================================

ansible_host: 172.20.20.26
router_id:    10.0.3.2
loopback0:    10.0.3.2/32
bgp_as:       65106
underlay_asn: 65102

spine01_p2p:      10.1.6.0/31
spine02_p2p:      10.2.6.0/31
spine01_leaf_ip:  10.1.6.1
spine02_leaf_ip:  10.2.6.1
spine01_ip:       10.1.6.0
spine02_ip:       10.2.6.0

esi_peer:             leaf-05
esi_id:               "0000:0000:0306:0000:0001"
esi_portchannel_id:   36
esi_lacp_id:          "0000.0306.0001"

spine01_interface: Ethernet1
spine02_interface: Ethernet2
peer_interface:    Ethernet10

active_vrfs:
  - name: STORAGE
    vrf_id: 300
    l3vni: 10300
    rd: "10.0.3.2:300"
    rt_import: "65000:10300"
    rt_export: "65000:10300"

active_vlans:
  - id: 300
    vni: 10300
    vrf: STORAGE
    anycast_gw_ip: 192.168.130.1/24
    anycast_gw_mac: 00:1c:73:00:03:00
    arp_suppression: true
    description: "STORAGE-CEPH-PUBLIC"
  - id: 310
    vni: 10310
    vrf: STORAGE
    anycast_gw_ip: 192.168.131.1/24
    anycast_gw_mac: 00:1c:73:00:03:10
    arp_suppression: true
    description: "STORAGE-CEPH-PRIVATE"

host_ports:
  - interface: Ethernet3
    description: "server-hpc-02 | Ceph public (VLAN 300)"
    mode: access
    vlan: 300
    mtu: 9000
    spanning_tree_portfast: true
    bpduguard: true

  - interface: Ethernet4
    description: "server-hpc-02 | Ceph replication (VLAN 310)"
    mode: access
    vlan: 310
    mtu: 9000
    spanning_tree_portfast: true
    bpduguard: true

  - interface: Ethernet5
    description: "server-storage-01 (VLAN 310)"
    mode: access
    vlan: 310
    mtu: 9000
    spanning_tree_portfast: true
    bpduguard: true

qos_policy_name: STORAGE-QOS
qos_ceph_replication_dscp: 18
bgp_community_storage: "65000:300"