frr version 9.1
frr defaults traditional
hostname leaf-09
log syslog informational
no ipv6 forwarding
!
vrf VRF-PEDAGOGY
 vni 50030
!
interface lo
 ip address 10.1.0.19/32
!
interface eth1
 description P2P to spine-01
 ip address 10.0.0.17/31
!
interface eth2
 description P2P to spine-02
 ip address 10.0.1.17/31
!
agentx
router bgp 65005
 no bgp ebgp-requires-policy
 bgp router-id 10.1.0.19
 bgp log-neighbor-changes
 bgp bestpath as-path multipath-relax
 neighbor FABRIC peer-group
 neighbor FABRIC bfd
 neighbor FABRIC timers 3 9
 neighbor FABRIC password ESI-BGP-INTERNAL
 neighbor FABRIC allowas-in 2
 neighbor 10.0.0.16 remote-as 65000
 neighbor 10.0.0.16 peer-group FABRIC
 neighbor 10.0.1.16 remote-as 65000
 neighbor 10.0.1.16 peer-group FABRIC
 !
 address-family ipv4 unicast
  network 10.1.0.19/32
  neighbor FABRIC soft-reconfiguration inbound
  maximum-paths 2
 exit-address-family
 !
 address-family l2vpn evpn
  neighbor FABRIC activate
  neighbor FABRIC allowas-in 2
  advertise-all-vni
 exit-address-family
!

router bgp 65005 vrf VRF-PEDAGOGY
 address-family ipv4 unicast
  redistribute connected
 exit-address-family
 address-family l2vpn evpn
  advertise ipv4 unicast
  rd 10.1.0.19:50030
  route-target both 65000:50030
 exit-address-family
!
line vty
